import fs from 'node:fs/promises';
import {Presentation,PresentationFile,FileBlob} from '@oai/artifact-tool';
import {finalizePresentation} from 'file:///C:/Users/vee/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='C:/Users/vee/source/repos/react_production_alpha',skill='C:/Users/vee/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const source=await PresentationFile.importPptx(await FileBlob.load('C:/Users/vee/Downloads/Prime-State-Systems-Preproduction.pptx'));
for(let i=0;i<3;i++){const b=await source.export({slide:source.slides.items[i],format:'png',scale:1});await fs.writeFile(root+`/.presentation-build/attached-${i}.png`,new Uint8Array(await b.arrayBuffer()));}
const proto=source.toProto();for(const s of proto.slides)s.elements=[];const p=Presentation.load(proto);
const B=(left,top,width,height)=>({left,top,width,height});
function tx(s,name,t,x,y,w,h,size=20,color='#0F0E0D',font='Arial'){const a=s.shapes.add({geometry:'textbox',name,position:B(x,y,w,h),fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:font,fontSize:size,color,autoFit:'none'};return a;}
function rule(s,x,y,w,color='#E0DDDA'){s.shapes.add({geometry:'rect',position:B(x,y,w,1),fill:color,line:{fill:'none',width:0}});}
function base(i,title,sub,dark=false){let s=p.slides.items[i];s.background.fill=dark?'#0F0E0D':'#FEFDFC';tx(s,'brand','PRIME STATE SYSTEMS',64,28,700,25,13,dark?'#BDB7AE':'#6B6762');tx(s,'page',`0${i+1}`,1160,28,60,25,13,dark?'#BDB7AE':'#6B6762');tx(s,'title',title,64,78,1150,65,39,dark?'#FEFDFC':'#0F0E0D','Georgia');tx(s,'intro',sub,64,152,1150,62,21,dark?'#D8D2C9':'#6B6762');rule(s,64,227,1152,dark?'#494640':'#E0DDDA');tx(s,'footer','PREPRODUCTION  /  Proposed scope and operating approach; client-specific requirements to be agreed',64,676,1152,25,12,dark?'#BDB7AE':'#6B6762');return s;}
let s=base(0,'A managed operating layer for local businesses','Standardize established business processes and turn research-informed methods into configured workflows, with a shared view of execution, outcomes and exceptions.');
const cols=[['01  MANAGED SERVICE','Design & implementation','Map the business pipeline and agree rules, responsible people and exceptions.\n\nConfigure integrations, routing and approvals around existing systems.\n\nValidate the workflow and establish an operating review cadence.','DELIVERABLE: Agreed process and pilot'],['02  PLATFORM VIEW','Inspect what actually ran','Review organization-specific workflows and their execution history.\n\nInspect status, duration, retries and processed or failed records.\n\nOpen execution steps and investigation notes when a run needs attention.','PLATFORM: Preproduction capability'],['03  ILLUSTRATIVE WORKFLOW','Document generation','Approved input → populate a versioned template → request approval → deliver the document → record the result.\n\nException: missing required data pauses the proposed process for review.\n\nReview run steps and failure details.','EXAMPLE: Configuration subject to scoping']];
cols.forEach(([lab,head,body,out],i)=>{let x=64+i*394;tx(s,'label'+i,lab,x,248,365,30,14,'#526859');tx(s,'heading'+i,head,x,288,365,50,25,'#0F0E0D','Georgia');tx(s,'body'+i,body,x,344,350,248,20,'#6B6762');rule(s,x,604,350);tx(s,'output'+i,out,x,618,354,43,16);});
s.speakerNotes.textFrame.setText('Sources: supplied product description; repository README.md; src/pages/HomePage.tsx; src/pages/DashboardPage.tsx; src/components/dashboard/RunDetail.tsx; src/pages/WorkflowsPage.tsx. Document generation is illustrative, not a live deployment. Missing-data handling is proposed configuration. Process and deliverables are a proposed service model, not a signed scope. Research-informed describes intended methodology; no specific study, measured result or production readiness is asserted.');
s=base(1,'The client journey: conversation to operations','Each stage produces a defined output. Access, process ownership and approval are established before the pilot moves into ongoing operation.');
const stages=[['Initial conversation','Understand priorities, current tools and the operational bottleneck.','Priority workflow and business owner'],['Process & scope','Map handoffs; agree rules, exclusions and success measures.','Scope and acceptance criteria'],['Client onboarding','Provision access; confirm systems, required data and contacts.','Access and onboarding checklist'],['Automation setup','Configure mappings, routing, approvals and exception paths.','Workflow ready for validation'],['Test & approve','Validate normal and failure cases; client approves launch.','Client launch approval gate'],['Operate & improve','Monitor activity, investigate exceptions and review outcomes.','Review cadence and improvement list']];
const coords=[[64,248],[458,248],[852,248],[852,458],[458,458],[64,458]];
stages.forEach(([head,body,out],i)=>{let [x,y]=coords[i];s.shapes.add({geometry:'rect',position:B(x,y,350,192),fill:'#F2F0ED',line:{fill:'#D0CBC4',width:1}});tx(s,'stage'+i,`0${i+1}  ${head}`,x+13,y+10,326,39,23,'#0F0E0D','Georgia');tx(s,'detail'+i,body,x+13,y+53,321,76,19,'#6B6762');tx(s,'result'+i,'OUTPUT  '+out,x+13,y+137,321,48,16,'#526859');});
for(const [x,y,g] of [[420,321,'rightArrow'],[814,321,'rightArrow'],[1016,443,'downArrow'],[814,531,'leftArrow'],[420,531,'leftArrow']])s.shapes.add({geometry:g,position:B(x,y,g==='downArrow'?21:31,g==='downArrow'?13:21),fill:'#526859',line:{fill:'none',width:0}});
s.speakerNotes.textFrame.setText('Proposed engagement process based on the user request: initial communication, onboarding, automation and ongoing operation. Informed by the repository HomePage Platform / Implementation / Operations service description. Outputs are proposed and require client agreement. Editable native flowchart.');
s=base(2,'A bounded pilot with explicit success criteria','Select one important workflow, agree the starting baseline, and evaluate its execution before committing to a wider rollout.',true);
const rows=[['Scope','One workflow, named owner, connected systems and agreed exclusions.','Client + Prime State'],['Readiness','Required access, suitable sample data, rules and exception ownership.','Client + Prime State'],['Validation','Normal cases, duplicates, missing data, failures and approval paths.','Prime State; client review'],['Evaluation','Review baseline versus pilot results; success thresholds agreed in advance.','Joint review'],['Expansion decision','Resolve open issues; agree support, next workflow and rollout scope.','Client approval']];
tx(s,'h1','PILOT REQUIREMENT',64,249,240,30,13,'#BDB7AE');tx(s,'h2','WHAT WILL BE AGREED OR REVIEWED',305,249,600,30,13,'#BDB7AE');tx(s,'h3','PROPOSED RESPONSIBILITY',962,249,260,30,13,'#BDB7AE');
rows.forEach(([a,b,c],i)=>{let y=295+i*65;tx(s,'r'+i,a,64,y,226,55,23,'#FEFDFC','Georgia');tx(s,'d'+i,b,305,y,615,56,20,'#D8D2C9');tx(s,'o'+i,c,962,y,254,55,18,'#D8D2C9');rule(s,64,y+58,1152,'#494640');});
tx(s,'decision','CLIENT INPUT  Nominate an owner; select a workflow; provide approved sample data and access.',64,635,1150,34,20,'#FEFDFC');
s.speakerNotes.textFrame.setText('Proposed pilot framework, not a commercial commitment. No numeric performance target is asserted. Baseline, evaluation measures, access, owners, acceptance criteria and launch decision need agreement. Sources: user preproduction status and product description; src/pages/HomePage.tsx engagement approach.');
const candidate=root+'/.presentation-build/reviewed-candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:root+'/outputs/presentations/Prime-State-Systems-Reviewed-v3.pptx',pythonExecutable:'C:/Users/vee/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],explicitTotalSlideCount:3,fontPolicy:{basis:'design',families:['Arial','Georgia']},verifyArtifactToolImport:true,receiptPath:root+'/.presentation-build/reviewed-validation-v3.json'});
for(let i=0;i<3;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(root+`/.presentation-build/reviewed-${i}.png`,new Uint8Array(await b.arrayBuffer()));}


