const n0=trigger({"type":"n8n-nodes-base.scheduleTrigger","version":1.3,"config":{"name":"Every 15 Minutes","parameters":{"rule":{"interval":[{"field":"minutes","minutesInterval":15}]}}}});
const n1=trigger({"type":"n8n-nodes-base.manualTrigger","version":1,"config":{"name":"Manual acceptance","parameters":{}}});
const n2=node({"type":"n8n-nodes-base.set","version":3.4,"config":{"name":"Annotate Follow-up Queue","parameters":{"mode":"raw","jsonOutput":expr("{{ {cursor:null} }}"),"options":{}}}});
const n3=node({"type":"n8n-nodes-base.postgres","version":2.6,"config":{"name":"Find Follow-up Candidates","parameters":{"operation":"executeQuery","query":"select automation.poll('lead_queue',$1,$2::uuid) as result","options":{"queryReplacement":expr("{{ ['n8n:'+$workflow.id+':'+$execution.id+':'+($json.cursor ?? 'start'), $json.cursor ?? null] }}")}},"credentials":{"postgres":{"id":"9NYei4dh7z08Xyf4","name":"Postgres account"}}}});
const n4=node({"type":"n8n-nodes-base.executeWorkflow","version":1.3,"config":{"name":"Report committed result","parameters":{"mode":"once","source":"database","workflowId":{"__rl":true,"mode":"id","value":"9zbbX0mzILkkXG1e"},"options":{"waitForSubWorkflow":true}}}});
const n5=ifElse({"version":2.3,"config":{"name":"More records","parameters":{"conditions":{"options":{"caseSensitive":true,"typeValidation":"strict"},"conditions":[{"leftValue":expr("{{ $json.result.has_more === true }}"),"rightValue":true,"operator":{"type":"boolean","operation":"true"}}],"combinator":"and"},"options":{}}}});
const n6=node({"type":"n8n-nodes-base.set","version":3.4,"config":{"name":"Next page","parameters":{"mode":"raw","jsonOutput":expr("{{ {cursor:$json.result.next_cursor} }}"),"options":{}}}});
const n7=node({"type":"n8n-nodes-base.set","version":3.4,"config":{"name":"Return queue outcome","parameters":{"mode":"raw","jsonOutput":expr("{{ $json }}"),"options":{}}}});
export default workflow("ankwO330MgME56EA","Platform - Lead Follow-up Queue").add(n0).to(n2).add(n1).to(n2).add(n2).to(n3).add(n3).to(n4).add(n4).to(n5).add(n5.onTrue(n6).onFalse(n7)).add(n6).to(n3);
