import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { scanRepository, stableJson, writeIfChanged, type RepositoryMap } from "./repo-map.ts";

const map = scanRepository();
const statePath = join(map.root, ".ai-state", "manifest.json");
const previous = existsSync(statePath) ? JSON.parse(readFileSync(statePath, "utf8")) as { files?: Record<string, string> } : {};
const current = Object.fromEntries(map.files.map((file) => [file.path, file.hash]));
const changed = map.files.filter((file) => previous.files?.[file.path] !== file.hash).map((file) => file.path);
const deleted = Object.keys(previous.files ?? {}).filter((path) => !(path in current));

function section(title: string, body: string): string { return `## ${title}\n\n${body.trim()}\n\n`; }
function bullets(items: string[]): string { return items.length ? items.map((item) => `- ${item}`).join("\n") : "- None detected."; }
function links(names: string[]): string { return names.length ? names.map((name) => `\`${name}\``).join(", ") : "None"; }
function writeKnowledge(map: RepositoryMap): void {
  const source = map.files.filter((file) => file.kind === "source" || file.kind === "function" || file.kind === "migration");
  const pages = source.filter((file) => file.path.includes("/pages/") || file.path.includes("/App.tsx"));
  const components = source.filter((file) => file.path.includes("/components/"));
  const hooks = source.filter((file) => file.path.includes("/hooks/"));
  const api = source.filter((file) => file.apiUsage.length || file.path.includes("/api/") || file.kind === "function");
  const db = source.filter((file) => file.databaseUsage.length || file.kind === "migration");
  const document = (name: string, title: string, content: string) => writeIfChanged(join(map.root, "knowledge", name), `# ${title}\n\n> Generated by \`npm run ingest\`. Source of truth remains the referenced implementation.\n\n${content.trim()}\n`);
  document("architecture.md", "Architecture", `${section("System shape", "React 19 + TypeScript + Vite frontend. Supabase provides authentication, database, storage, and Edge Functions. React Router owns navigation; Zustand owns auth state; React Query owns server cache.")}${section("Boundaries", bullets(["UI: `src/pages/` and `src/components/`", "State: `src/store/` and `src/hooks/`", "Integration: `src/api/` and `supabase/functions/`", "Persistence: `supabase/migrations/`", "Agent operations: Supabase/database MCP for local and staging schema work; Playwright MCP on demand for UI smoke tests"] ))}${section("Related", "See [state](state.md), [api](api.md), [database](database.md), and [auth](auth.md). Operational MCP policy: `docs/mcp-operations.md`.")}`);
  document("features.md", "Features", `${section("Public experience", "Landing page, integrations orbit, ROI calculator, FAQ, contact form, and login entry point.")}${section("Authenticated experience", "Dashboard exposes client automation metrics and workflow activity. Workflows exposes configured automation services and runs.")}${section("Automation contract", "n8n sends `event_id`, `client_id`, `feature_type`, `workflow_name`, and `status` to `supabase/functions/ingest-run/index.ts`; the database migration enforces idempotency and enum constraints.")}`);
  document("routes.md", "Routes", bullets(map.files.flatMap((file) => file.routes.map((route) => `\`${route}\` — ${file.path}`))) + "\n\nProtected routes are guarded by `ProtectedRoute` in `src/App.tsx`. See [auth](auth.md).");
  document("pages.md", "Pages", bullets(pages.map((file) => `\`${file.path}\` — exports ${links(file.exports)}`)));
  document("components.md", "Components", bullets(components.map((file) => `\`${file.path}\` — ${file.exports.length ? `exports ${links(file.exports)}` : "shared implementation"}; uses ${links(file.referencedComponents)}`)));
  document("hooks.md", "Hooks", bullets(hooks.map((file) => `\`${file.path}\` — exports ${links(file.exports)}; calls ${links(file.referencedHooks)}`)));
  document("contexts.md", "Contexts", "No React Context provider was detected. Authentication is centralized in Zustand (`src/store/authStore.ts`).");
  document("services.md", "Services", bullets(api.map((file) => `\`${file.path}\` — API usage: ${links(file.apiUsage)}`)));
  const apiContent = section("Browser clients", bullets(source.filter((file) => file.path.includes("/api/")).map((file) => `\`${file.path}\` — ${links(file.exports)}`))) + section("Edge functions", bullets(source.filter((file) => file.kind === "function").map((file) => `\`${file.path}\``))) + section("MCP boundary", "Supabase/database MCP access is limited to local and staging environments. Playwright/browser MCP is used only for local or staging smoke tests. Filesystem and Git remain Codex-native capabilities.") + section("Security", "Browser code uses public Supabase credentials from `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY`. Webhook and admin secrets stay in Edge Function environment variables.");
  document("api.md", "API", apiContent);
  document("database.md", "Database", bullets(db.map((file) => `\`${file.path}\` — ${links(file.databaseUsage)}`)) + "\n\nThe generated database index contains file-level usage. Verify schema semantics in the SQL migrations before changing client isolation or automation ingestion. Use the Supabase/database MCP or `npm run db:dry-run` only against local or staging; production is outside the default MCP boundary.");
  document("auth.md", "Authentication", "`src/main.tsx` bootstraps Supabase auth and writes session state to `src/store/authStore.ts`. `useAuth` exposes the session to pages. `ProtectedRoute` redirects unauthenticated users to `/login`. Invite acceptance is handled at `/accept-invite`.");
  document("state.md", "State", "Zustand stores auth state. React Query hooks (`src/hooks/useClient.ts`, `useRuns.ts`, `useWorkflows.ts`, `useAnalytics.ts`, `useClientServices.ts`) fetch and cache Supabase data. Local component state handles transient UI concerns.");
  document("styling.md", "Styling", "Global styles live in `src/index.css` and `src/styles/globals.css`; design tokens live in `src/styles/tokens.ts`. Tailwind CSS is configured through Vite. Motion primitives live under `src/components/motion/`.");
  document("dependencies.md", "Dependencies", bullets(Object.entries(map.dependencies).sort(([a], [b]) => a.localeCompare(b)).map(([name, version]) => `\`${name}\` ${version}`)));
  document("folder_structure.md", "Folder Structure", bullets([...new Set(map.files.map((file) => file.path.split("/").slice(0, -1).join("/") || "."))].sort().map((path) => `\`${path}/\``)));
  document("glossary.md", "Glossary", "- **Client**: authenticated tenant represented by a Supabase `clients` row.\n- **Workflow**: configured automation connected to a client.\n- **Run**: one reported workflow execution, keyed by `event_id`.\n- **Feature type**: product-facing automation category shown in the dashboard.\n- **Edge Function**: server-side Supabase function used for trusted integrations.");
}

writeKnowledge(map);
// Files under docs/ are authored and reviewed like code. Keep them out of the
// generated pass so refreshing repository knowledge cannot replace useful
// specifications, ADRs, or runbooks with placeholders.
writeIfChanged(statePath, stableJson({ files: current, changed, deleted }));
console.log(`Ingested ${map.files.length} files. Changed: ${changed.length}; deleted: ${deleted.length}.`);
