import { join } from "node:path";
import { writeIfChanged, type FileRecord, type RepositoryMap } from "./repo-map.ts";

const section = (title: string, body: string) => `## ${title}\n\n${body.trim()}\n\n`;
const bullets = (items: string[]) => items.length
  ? items.map((item) => `- ${item}`).join("\n")
  : "No text matches in the scanned files. This is not proof of absence.";
const names = (items: string[]) => items.length ? items.map((item) => `\`${item}\``).join(", ") : "none";
const sourceLink = (file: FileRecord) => `[${file.path}](../../${file.path.split("/").map(encodeURIComponent).join("/")})`;

export function writeKnowledge(map: RepositoryMap): void {
  const source = map.files.filter((file) => ["source", "function", "migration"].includes(file.kind));
  const inPath = (part: string) => source.filter((file) => file.path.includes(part));
  const inventory = (files: FileRecord[]) => bullets(files.map((file) => `${sourceLink(file)} — export-name matches: ${names(file.exports)}`));
  const document = (name: string, title: string, content: string) => writeIfChanged(
    join(map.root, "docs", "knowledge-base", name),
    `# ${title}\n\n> Generated by \`npm run ingest\`. Approximate source-text index; matches may include comments/examples and miss aliases or dynamic behavior. This is not runtime, authorization, or completeness evidence. See [document authority](../README.md#authority-and-status) and [scanner](../../scripts/repo-map.ts).\n\n${content.trim()}\n`,
  );

  document("architecture.md", "Architecture navigation",
    section("Scanned implementation files", bullets([
      `Source files: ${source.filter((file) => file.kind === "source").length}`,
      `Edge Function files: ${source.filter((file) => file.kind === "function").length}`,
      `Migration files: ${source.filter((file) => file.kind === "migration").length}`,
    ])) + section("Authored interpretation", "See [architecture](../README.md#architecture), [folder boundaries](../adrs/folders.md), and [database decisions](../adrs/database.md). Counts describe scanned files, not deployed services."));
  document("features.md", "Feature navigation",
    section("Page-file inventory", inventory(inPath("/pages/"))) +
    section("Required and proposed behavior", "See [feature specifications](../README.md#feature-specifications) and the [roadmap](../future-product-roadmap.md). File presence does not establish a reachable or completed feature."));
  document("routes.md", "Route and navigation text matches",
    bullets(source.flatMap((file) => file.routes.map((route) => `\`${route}\` — ${sourceLink(file)}`))) +
    "\n\nMatches include route declarations and navigation targets; they are not an authoritative route table. Access protection is not evaluated. Inspect [routing decisions](../adrs/routing.md) and the actual wrappers before drawing an access conclusion.");
  document("pages.md", "Page files", inventory(inPath("/pages/")));
  document("components.md", "Component files", bullets(inPath("/components/").map((file) =>
    `${sourceLink(file)} — export-name matches: ${names(file.exports)}; JSX component matches: ${names(file.referencedComponents)}`)));
  document("hooks.md", "Hook files", bullets(inPath("/hooks/").map((file) =>
    `${sourceLink(file)} — export-name matches: ${names(file.exports)}; hook-call matches: ${names(file.referencedHooks)}`)));

  const contextCandidates = source.map((file) => ({
    file,
    providers: file.referencedComponents.filter((name) => /Provider$/.test(name)),
    contextNames: file.symbols.filter((name) => /Context/.test(name)),
  })).filter(({ providers, contextNames }) => providers.length || contextNames.length);
  document("contexts.md", "Context and provider candidates", bullets(contextCandidates.map(({ file, providers, contextNames }) =>
    `${sourceLink(file)} — provider-name JSX matches: ${names(providers)}; context-name symbol matches: ${names(contextNames)}`)) +
    "\n\nNames are candidates only; they do not establish React Context creation or ownership. See [state decisions](../adrs/state.md) for the authored model.");
  document("services.md", "API usage candidates", bullets(source.filter((file) => file.apiUsage.length).map((file) =>
    `${sourceLink(file)} — API text matches: ${names(file.apiUsage)}`)));
  document("api.md", "API navigation",
    section("Browser API files", inventory(inPath("/api/"))) +
    section("Edge Function files", inventory(source.filter((file) => file.kind === "function"))) +
    section("Contracts and authorization", "See [API decisions](../adrs/api.md), [ingestion](../specs/automation-run-ingestion.md), and [invitation](../specs/client-invitation.md). The inventory does not validate endpoint authentication or execution."));
  document("database.md", "Database text matches", bullets(source.filter((file) => file.databaseUsage.length || file.kind === "migration").map((file) =>
    `${sourceLink(file)} — database text matches: ${names(file.databaseUsage)}`)) +
    "\n\nThis is not the applied schema or proof of RLS. See [canonical run ownership](../architecture/canonical-workflow-runs.md), [migration procedure](../runbooks/database-migrations.md), and [executable RLS testing](../runbooks/rls-testing.md).");
  document("auth.md", "Authentication navigation", inventory(source.filter((file) => /auth/i.test(file.path))) +
    "\n\nFiles are selected by path text. See [authentication decisions](../adrs/authentication.md) for session and access boundaries.");
  document("state.md", "State navigation", inventory([...inPath("/store/"), ...inPath("/hooks/")]) +
    "\n\nSee [state decisions](../adrs/state.md) for ownership, cache behavior, and limitations.");
  document("styling.md", "Styling navigation", inventory(map.files.filter((file) => file.extension === ".css" || file.path.startsWith("src/styles/") || file.path.startsWith("src/components/motion/"))) +
    "\n\nSee [styling decisions](../adrs/styling.md). The inventory does not prove token consistency or accessible rendering.");
  document("dependencies.md", "Declared dependency ranges", bullets(Object.entries(map.dependencies).sort(([a], [b]) => a.localeCompare(b)).map(([name, version]) =>
    `\`${name}\` ${version}`)) + "\n\nRanges come from package.json, not the installed dependency tree or an advisory audit.");
  document("folder_structure.md", "Scanned folder inventory", bullets([...new Set(map.files.map((file) =>
    file.path.split("/").slice(0, -1).join("/") || "."))].sort().map((path) => `\`${path}/\``)) +
    "\n\nExcluded directories are defined in the scanner. See [repository boundaries](../adrs/folders.md) for authored guidance.");
  document("glossary.md", "Glossary navigation", "Domain definitions are authored in the [domain glossary](../architecture/glossary.md); they are not inferred by this generator.");

  for (const [name, target] of [["architecture.md", "architecture.md"], ["knowledge.md", "api.md"]]) {
    writeIfChanged(join(map.root, "docs", "generated", name),
      `# Legacy generated entry point\n\n> Maintained by \`npm run ingest\`. This location no longer contains a separate implementation snapshot.\n\nUse the [current generated navigation](../knowledge-base/${target}) and [authored documentation index](../README.md).\n`);
  }
}
